### Your name:

<pre> SV</pre>

### Collaborators:

<pre> Enter the name of the people you worked with if any</pre>


In [22]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import math

Markdown referece can be found here:
    http://nestacms.com/docs/creating-content/markdown-cheat-sheet

Q1. Why would it be a problem if our training set and test set are the same.

<p>In general, the objective of machine learning is to build a <b>generalized model</b> capable of making decisions or predictions regarding 'unseen' data based on 'learnings' from a training dataset. </p>

<p>Most real world systems change on a constant basis and consequently the data that they generate also changes. While 
building a machine learning model that consumes such data, it is important to acknowledge and account for the 'changing' nature of the data by using a completely unseen dataset to evaluate the performance of the model. If we were to both train and test 
the model on the exact same data points, the model would undoubtedly seem to perform very well since it would have identified
the nuances within the training data and when these same data points are presented again, produce an output that very closely
matches the expected value. This is known as <b><i>'over-fitting'</i></b>.</p>

<p>To get a more realistic measure of performance, therefore, it is important to keep a portion of the training dataset <i>hidden</i> from the model and train it on the remaining data. This technique is called the <b><i>'holdout method'</i></b>. One could go a step further and improve the results of this technique by performing multiple iterations of this method, each time using a different part of the data to train and the remaining to test the model. This is known as <b>k-fold cross-validation</b>.</p>

Q2 [OPTIONAL]. Explain step by step the process to select k in the k-nearest neighbor algorithm (pseudocode) 

<pre> ENTER SOLUTION HERE </pre>

Q3. For the k-nearest regression. What happends when k = n. Where n is equal to the training size.

<p>The choice of k value plays a critical role in the output of the K-nearest neighbors (KNN) algorithm. In essence, the KNN algorithm divides the feature space into 'classes' of related points. Choosing a low K value (for ex. k=1) would result in very sharp class boundaries and in general lead to overfitting. There would also be a greater amount of variance among the classes but lower bias in terms of mis- classifying or regressing a test point.</p> 
<p>On the other hand, choosing a very high k value (for ex. k=n, where n is equal to the size of the training dataset) would result in highly smoothed class boundaries. There will be a lower amount of variance overall but a greater level of bias leading to greater levels of mis-classification or inaccurate regression of a test point. </p>

Q4. Define a function that takes a 1-d numpy array, a parameter k, and a number p.
The function returns an estimate equal to the mean of the closest k points to the number p

In [81]:
def k_neighbor(input_data, k, p):
    """Returns the k-neighbor estimate for p using data input_data.
    
    Keyword arguments:
    input_data -- numpy array of all the data
    k -- Number of k
    p -- input values
    
    If you make assumptions please explain them in the comments. i.e. tie breaking strategy.
    """
    
    #YOUR CODE HERE
    # STEP 1: compute distances to all points in the feature space as absolute value of difference
    # between p and each point
    distances = [(i, abs(p - i)) for i in data]
 
    # STEP 2: sort in ascending order of distances
    # Tie Breaker logic: we sort the list of tuples first by absolute distance and 
    # then by the value of each point. This way, if two points lie at the same distance from
    # the test point, the one with lower value will be given preference i.e. we are making a 'conservative'
    # estimation.
    distances_sorted = sorted(distances, key=lambda tup: (tup[1], tup[0]))
    
    # STEP 3: find k closest points
    k_closest_points = ([tup[0] for tup in distances_sorted[:k]])
    print('Closest', k, 'points to', p, ':', k_closest_points)
    
    # STEP 4: find mean of k closes points
    k_neighbor_estmt = np.mean(k_closest_points)
    
    #return answer
    return k_neighbor_estmt

In [82]:
#Evaluate
data = np.array([1,3,4,5,7,8,11,12,13,15,19,24,25,29,40])
print(k_neighbor(input_data=data, k=3, p=5))
print(k_neighbor(input_data=data, k=2, p=15))
print(k_neighbor(input_data=data, k=3, p=25))
print(k_neighbor(input_data=data, k=1, p=55))
print(k_neighbor(input_data=data, k=3, p=55))
print(k_neighbor(input_data=data, k=10, p=55))

Closest 3 points to 5 : [5, 4, 3]
4.0
Closest 2 points to 15 : [15, 13]
14.0
Closest 3 points to 25 : [25, 24, 29]
26.0
Closest 1 points to 55 : [40]
40.0
Closest 3 points to 55 : [40, 29, 25]
31.3333333333
Closest 10 points to 55 : [40, 29, 25, 24, 19, 15, 13, 12, 11, 8]
19.6


In [1]:
#Enter your observations and comments here
# (1) Low values of K, for example k = 1 as in example 4 seems to result in more accurate regressing. 
# (2) High values of K, for example k = 10 as in the last example seems to lead to very inaccurate 
# regressing: considerable difference between the test point of 55 and the output of 19.6

Q5. Similar to Q4 but for the n dimentional case. 

In [117]:
def l1_norm(a,b):
    """Returns the l1 norm (a,b)"""

    return np.sum([abs(x[0] - x[1]) for x in zip(a, b)])
    
def l2_norm(a,b):
    """Returns the l2 norm (a,b)""" 
    
    return np.sqrt(np.sum([np.square(x[0] - x[1]) for x in zip(a, b)]))
    
def k_neighbor_nd(input_data, k, p, metric='l1', mode='mean'):
    """Returns the k-neighbor estimate for p using data input_data.

    Keyword arguments:
    input_data -- numpy array of all the data
    k -- Number of k
    p -- input values
    metric -- l1 or l2. l1 norm or l2 norm https://en.wikipedia.org/wiki/Norm_(mathematics)
    mode -- estimator possible values = 'mean', 'median', 'max'
    
    Implement the l1 and l2 norms
    for mean, median and max, use np.mean, np.median and np.max
    """
    
    #YOUR CODE HERE
    # STEP 0: define function maps
    metric_func_map = {'l1': l1_norm,
                     'l2': l2_norm}
    mode_func_map = {'mean': np.mean,
                     'median': np.median,
                     'max': np.max}
    
    # STEP 1: compute distances from input p to all points in the feature space
    # based on input.
    distances = [(y[1], norm_func_map[metric](y[0], y[1])) for y in [(p, x) for x in data_4d]]
        
    # STEP 2: sort in ascending order of distances
    distances_sorted = sorted(distances, key=lambda tup: tup[1])
    print(distances_sorted)
    
    # STEP 3: find k closest points
    # Tie-breaker logic: here in case of a tie between two n-dimensional points, we pick one at random i.e.
    # in the order that the sort function ordered the points after sorting by distance
    k_closest_points = ([tup[0] for tup in distances_sorted[:k]])
    print('Closest', k, 'points to', p, ':', k_closest_points)
    
    # STEP 4: find mean/median/max of k closest points based on inpit
    print('Using mode:', mode )
    k_neighbor_estmt = [x for x in mode_func_map[mode](k_closest_points, axis=0)]
    
    #return answer
    return k_neighbor_estmt
   

In [93]:
data_4d = np.array([[4, 1, 2, 1], [1, 4, 2, 0], [3, 3, 1, 1], 
        [4, 0, 0, 0], [1, 2, 0, 0], [3, 4, 2, 3], 
        [2, 4, 4, 2], [2, 1, 4, 1], [3, 3, 2, 4], 
        [4, 3, 0, 4], [2, 2, 4, 0],[4, 3, 0, 2], 
        [4, 3, 0, 2], [0, 3, 4, 2]])

In [114]:
#Evaluate
data = np.array([1,3,4,5,7,8,11,12,13,15,19,24,25,29,40])
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 1, 4, 3], metric='l1', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=2, p=[4, 4, 0, 0], metric='l1', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 2, 2, 4], metric='l1', mode='max'))
print(k_neighbor_nd(input_data=data_4d, k=1, p=[2, 3, 3, 4], metric='l1', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 3, 3, 4], metric='l1', mode='median'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 1, 4, 3], metric='l2', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=2, p=[4, 4, 0, 0], metric='l2', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 2, 2, 4], metric='l2', mode='max'))
print(k_neighbor_nd(input_data=data_4d, k=1, p=[2, 3, 3, 4], metric='l2', mode='mean'))
print(k_neighbor_nd(input_data=data_4d, k=3, p=[2, 3, 3, 4], metric='l2', mode='median'))

Closest 3 points to [2, 1, 4, 3] : [array([2, 1, 4, 1]), array([2, 4, 4, 2]), array([2, 2, 4, 0])]
Using mode: mean
[2.0, 2.3333333333333335, 4.0, 1.0]
Closest 2 points to [4, 4, 0, 0] : [array([4, 3, 0, 2]), array([4, 3, 0, 2])]
Using mode: mean
[4.0, 3.0, 0.0, 2.0]
Closest 3 points to [2, 2, 2, 4] : [array([3, 3, 2, 4]), array([3, 4, 2, 3]), array([4, 3, 0, 4])]
Using mode: max
[4, 4, 2, 4]
Closest 1 points to [2, 3, 3, 4] : [array([3, 3, 2, 4])]
Using mode: mean
[3.0, 3.0, 2.0, 4.0]
Closest 3 points to [2, 3, 3, 4] : [array([3, 3, 2, 4]), array([3, 4, 2, 3]), array([2, 4, 4, 2])]
Using mode: median
[3.0, 4.0, 2.0, 3.0]
Closest 3 points to [2, 1, 4, 3] : [array([2, 1, 4, 1]), array([0, 3, 4, 2]), array([2, 4, 4, 2])]
Using mode: mean
[1.3333333333333333, 2.6666666666666665, 4.0, 1.6666666666666667]
Closest 2 points to [4, 4, 0, 0] : [array([3, 3, 1, 1]), array([4, 3, 0, 2])]
Using mode: mean
[3.5, 3.0, 0.5, 1.5]
Closest 3 points to [2, 2, 2, 4] : [array([3, 3, 2, 4]), array([3, 4, 2,

In [ ]:
#Enter your observations and comments here

Q6[Optional]. Read the documentation on KNeighborsRegressor

http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html
    
Explore the source code:
    https://github.com/scikit-learn/scikit-learn/blob/ef5cb84a/sklearn/neighbors/regression.py
        
How different it is from your implementation? How well can you follow the code? Did you learn something new?

<pre> ENTER SOLUTION HERE </pre>

In [ ]:
#Solution

#Question 1
Remember the puporse of machine learning is to be able to generalize with data the algorithm has never seen. 
If you train and test with the same data, you are evaluating the performance on the same peace of data. 
Therefore, you would not be able to know whether the algorithm actually would perform on unseen data. 20 / 20

#Question 3
If we set k = n, the prediction will be the same for any new data point -> Average of all poins in the training set. 15 / 20

#Question 4
Code
arr = (((p - input_data)2))0.5
ind = np.argpartition(arr, k)[:k]
return(np.mean(input_data[ind]))
Results
5.333333333333333
14.0
26.0
40.0
31.333333333333332
> 19.6

30 / 30

#Question 5
Code
def l1_norm(a,b): """Returns the l1 norm (a,b)""" return sum(abs(a - b))

def l2_norm(a,b): """Returns the l2 norm (a,b)""" return (sum((b - a)2))0.5

def k_neighbor_nd(input_data, k, p, metric='l1', mode='mean'): """Returns the k-neighbor estimate for p using data input_data.

Keyword arguments:
input_data -- numpy array of all the data
k -- Number of k
p -- input values
metric -- l1 or l2. l1 norm or l2 norm https://en.wikipedia.org/wiki/Norm_(mathematics)
mode -- estimator possible values = 'mean', 'median', 'max'

Implement the l1 and l2 norms
for mean, median and max, use np.mean, np.median and np.max
"""

#YOUR CODE HERE
if metric == 'l1':
    arr = np.zeros(0)
    for i in range(0, input_data.shape[0]):
        arr = np.append(arr, l1_norm(p, input_data[i]))

if metric == 'l2':
    arr = np.zeros(0)
    for i in range(0, input_data.shape[0]):
        arr = np.append(arr, l2_norm(p, input_data[i]))


ind = np.argpartition(arr, k)[:k]

if mode == 'mean':
    return(np.mean(input_data[ind], axis = 0))

if mode == 'median':
    return(np.median(input_data[ind], axis = 0))

if mode == 'max':
    return(np.max(input_data[ind], axis = 0))
Results
[ 2. 2.33333333 4. 1. ]
[ 4. 3. 0. 2.]
[4 4 2 4]
[ 3. 3. 2. 4.]
[ 3. 4. 2. 3.]
[ 1.33333333 2. 4. 1. ]
[ 3.5 3. 0.5 1.5]
[4 4 2 4]
[ 3. 3. 2. 4.]
[ 3. 4. 2. 3.]

30 / 30

Total : 95 / 100